### ISSUE TITLE
Updates to vignette

### ISSUE THREAD

**Issue by numbersman77** [insightsengineering/simIDM#57]
- [x] Add rpact code to compute sample size for PFS and OS using Schoenfeld:

`library(rpact)

# PFS
pfs_ss <- getSampleSizeSurvival(lambda2 = sum(hsc[s, c("h01", "h02")]), hazardRatio = hr_pfs[s],
                                    accrualTime = 0, accrualIntensity = 500,
                                    maxNumberOfSubjects = 1000, sided = 1, alpha = alphaPFS / 2, beta = 0.2)
pfs_ss <- ceiling(pfs_ss$eventsFixed)
pfs_ss

# OS
os_ss <- getSampleSizeSurvival(lambda2 = sum(hsc[s, c("h01", "h02")]), hazardRatio = os_ahr,
                                accrualTime = 0, accrualIntensity = 500,
                                maxNumberOfSubjects = 2000, sided = 1, alpha = alphaOS / 2, beta = 0.2)
os_ss <- ceiling(os_ss$eventsFixed)
os_ss`

- [x] Use an example from the paper and reproduce numbers in Table 2.
- [x] Add indicator of progress of simulations.
- [x] Computation of AHR: why over many trials? Is this not a deterministic number? --> compute using integrals
- [x] Add function powerIDM and streamline vignette using it.
- [x] For powerIDM: add P(PFS sig), P(OS sig), P(both sig).

**Comment by holgstr** [comment]
@numbersman77 I'm almost done updating the vignette. I have used scenario 2 as an example - any chance you have the image that plots transition hazards, hazard functions, hazard ratios etc. for this scenario? This should be figure 7 in the [paper](https://arxiv.org/pdf/2301.10059.pdf). Otherwise I can take a screenshot from the PDF..
